#!/usr/bin/python

# tranpose-file.py - Transpose csv files

import pandas as pd
import argparse
parser = argparse.ArgumentParser(description='Transpose csv files')
parser.add_argument('input', type=str, help='Specify csv file to transpose')
parser.add_argument('output', type=str, help='Output to another csv file')
args = parser.parse_args()

csv_input  = args.input
csv_output = args.output
pd.read_csv(csv_input, header=None).T.dropna().astype(int).to_csv(csv_output, header=False, index=False)
