#!/bin/bash

archive_branch() {
    # Source: https://gist.github.com/zkiraly/c378a1a43d8be9c9a8f9
    # Usage: archive_branch sprintjuly2010
    # This will remove the branch you want to archive and create a tag with its content in the following format:
    # archive/2020-01-08-sprintjuly2010

    date=$(date '+%Y-%m-%d')
    git checkout master
    git tag archive/$date-$1 $1
    git branch -D $1
    git branch -d -r origin/$1
    git push --tags
    git push origin :$1
}

show_usage() {
    echo "      archive-branch - Archive old git branches"
    echo "              Usage: git archive-branch [branch]\n"
    echo "archive-branch tags git branches for archiving, and then deletes the branch from the current git index."
    echo ""
}

if [[ -z $1 ]];then 
    show_usage
else
    read -p "Are you sure you want to do this? [y/n]: " user_choice
    if [[ $user_choice == "y" ]]; then
        archive_branch $1
    else
        exit 0
    fi
fi
