[shortpaths]
cocsettings = '~/.config/${env:EDITOR}/coc-settings.json'
snips       = '~/.config/coc/ultisnips'
bin         = '~/.local/bin'
share       = '~/.local/share'
excludes    = '$share/excludes'
work        = '${env:HOME}/Workspace'
ai          = '$work/ai'
apps        = '$work/apps'
draw        = '$work/drawing'
horse       = '$work/horse'
notes       = '$work/notes'
cnotes      = '$notes/cocanotes'
pg          = '$work/playground'
school      = '$work/school'
mitcw       = '$school/MIT OpenCourseWare'
uni         = '$school/University'
re          = '$work/security/re'
