#!/usr/bin/bash

# Show the mean and max volume of a file

show_full_output=false # Show full ffmpeg output 
input="$1"

# Toggle between full output and shortened outputs
if [[ "$input" == "-f" ]]  ||  [[ "$input" == "--full" ]]; then
    echo "Showing full output"
    show_full_output=true
    shift
fi

vol() {
    # Show the mean and max volume of a file
    file="$1"
    if [[ ! -z "$file" ]]; then
        options=('-i' "$file" '-filter:a' 'volumedetect' '-f' 'null' '/dev/null 2>&1')
        if [ "$show_full_output" = true ]; then
            ffmpeg -i "$file" -filter:a volumedetect -f null /dev/null 2>&1
        else
            output=$(ffmpeg -i "$file" -filter:a volumedetect -f null /dev/null 2>&1 | grep "mean_volume\|max_volume" | cut -d ' ' -f5)
            echo $output # Print on one line
        fi
    fi
}

for file in "$@"
do
    vol "$file"
done
