#!/usr/bin/python

import urllib.request
import toml
import pathlib

def read_file(fp: str) -> str:
    file = open(fp, 'r')
    res = file.read()
    file.close()
    return res


cfg     = toml.loads(read_file(pathlib.Path("~/.config/polybar/weather.toml").expanduser()))['weather']
api     = cfg['api']
key     = cfg['key']
city    = cfg['city']
units   = cfg['units']

weather = eval(str(urllib.request.urlopen('{}/weather?appid={}&id={}&units={}'.format(api, key, city, units)).read())[2:-1])
currWeather = weather['weather'][0]

main = currWeather['main'] # Forecast
description = currWeather['description']

icon = ''
if main == 'Drizzle':
  icon = ' '
elif main == 'Rain':
  icon = ' '
elif main == 'Thunderstorm':
  icon = ' '
elif main == 'Snow':
  icon = ' '
elif main == 'Mist':
  icon = '  '
elif main == 'Clear':
  icon = ' '
elif main == 'Clouds':
  icon = ' '
elif main == 'Haze':
  icon = ' '

info = description.capitalize()
temp = int(float(weather['main']['temp']))
print('%s %s, %i °C' % (icon, main, temp))
